//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.Abouts = new HashSet<About>();
            this.Ads = new HashSet<Ad>();
            this.Agents = new HashSet<Agent>();
            this.Application_Supporters = new HashSet<Application_Supporters>();
            this.Application_Vendor = new HashSet<Application_Vendor>();
            this.Contents = new HashSet<Content>();
            this.Events = new HashSet<Event>();
            this.Geolocations = new HashSet<Geolocation>();
            this.Images = new HashSet<Image>();
            this.MobileUsers = new HashSet<MobileUser>();
            this.QAs = new HashSet<QA>();
            this.Sequences = new HashSet<Sequence>();
            this.Texts = new HashSet<Text>();
            this.VideoAudios = new HashSet<VideoAudio>();
            this.Voices = new HashSet<Voice>();
            this.DeviceTypes = new HashSet<DeviceType>();
        }
    
        public int Application_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Company_Id { get; set; }
        public string ApplicationToken { get; set; }
    
        public virtual ICollection<About> Abouts { get; set; }
        public virtual ICollection<Ad> Ads { get; set; }
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual ICollection<Application_Supporters> Application_Supporters { get; set; }
        public virtual ICollection<Application_Vendor> Application_Vendor { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Content> Contents { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Geolocation> Geolocations { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<MobileUser> MobileUsers { get; set; }
        public virtual ICollection<QA> QAs { get; set; }
        public virtual ICollection<Sequence> Sequences { get; set; }
        public virtual ICollection<Text> Texts { get; set; }
        public virtual ICollection<VideoAudio> VideoAudios { get; set; }
        public virtual ICollection<Voice> Voices { get; set; }
        public virtual ICollection<DeviceType> DeviceTypes { get; set; }
    }
}
