//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Applications = new HashSet<Application>();
            this.Supporters = new HashSet<Supporter>();
        }
    
        public int Company_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<int> Admin_Id { get; set; }
        public string Company_Url { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Supporter Supporter { get; set; }
        public virtual ICollection<Supporter> Supporters { get; set; }
    }
}
