//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string abbreviation { get; set; }
        public string code { get; set; }
        public Nullable<int> ContinentID { get; set; }
        public string Continent_Name { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Continent Continent { get; set; }
    }
}
