//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geolocation
    {
        public Geolocation()
        {
            this.Geolocations1 = new HashSet<Geolocation>();
        }
    
        public int GeolocationID { get; set; }
        public string Name { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public Nullable<double> Altitude { get; set; }
        public string Description { get; set; }
        public int Application_Id { get; set; }
        public Nullable<int> Parent_Geo_Id { get; set; }
        public Nullable<double> Range { get; set; }
        public int DownloadTime { get; set; }
        public Nullable<int> ContinentID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Continent Continent { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<Geolocation> Geolocations1 { get; set; }
        public virtual Geolocation Geolocation1 { get; set; }
    }
}
