//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hint
    {
        public int Hint_Id { get; set; }
        public string Description { get; set; }
        public int QA_Id { get; set; }
    
        public virtual QA QA { get; set; }
    }
}
