//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Copy_IMR_TestEntities6 : DbContext
    {
        public Copy_IMR_TestEntities6()
            : base("name=Copy_IMR_TestEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Ad> Ads { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Application_Supporters> Application_Supporters { get; set; }
        public virtual DbSet<Application_Vendor> Application_Vendor { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<ContentType> ContentTypes { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DeviceType> DeviceTypes { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Geolocation> Geolocations { get; set; }
        public virtual DbSet<Hint> Hints { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<MobileUser> MobileUsers { get; set; }
        public virtual DbSet<QA> QAs { get; set; }
        public virtual DbSet<QuestionType> QuestionTypes { get; set; }
        public virtual DbSet<Sequence> Sequences { get; set; }
        public virtual DbSet<SequenceType> SequenceTypes { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Supporter_Roles> Supporter_Roles { get; set; }
        public virtual DbSet<Supporter> Supporters { get; set; }
        public virtual DbSet<Text> Texts { get; set; }
        public virtual DbSet<Utility> Utilities { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VideoAudio> VideoAudios { get; set; }
        public virtual DbSet<Voice> Voices { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
