//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA
    {
        public QA()
        {
            this.Hints = new HashSet<Hint>();
        }
    
        public int QAID { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<int> Type_Id { get; set; }
        public int Application_Id { get; set; }
        public Nullable<int> Geo_Id { get; set; }
        public int DownloadTime { get; set; }
        public Nullable<int> Sequence_Num { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<Hint> Hints { get; set; }
        public virtual QuestionType QuestionType { get; set; }
    }
}
